### expenses
GET http://localhost:3000/expenses
Accept: application/json

### expense by id
GET http://localhost:3000/expenses/5
Accept: application/json

### expenses paginated
GET http://localhost:3000/expenses/paginated/1/5
Accept: application/json


### create expense
POST http://localhost:3000/expenses
Content-Type: application/json

{
  "description": "Internet hogar y mobil",
  "amount": 38,
  "category": "Servicios",
  "billType": "Fijo"
}   

### delete expense
DELETE http://localhost:3000/expenses/5
Accept: application/json

### delete from id to id expense
DELETE http://localhost:3000/expenses?from=13&to=17
Accept: application/json

### create expense from json file
POST http://localhost:3000/expenses/from-value-array
Content-Type: application/json

[
  ["Santa Isabel s4", "22714", "Supermercado", "Variable", "2026-03-01"],
  ["Mercado libre", "5580", "Otros", "Variable", "2026-03-01"],
  ["Banco Falabella", "179240", "Credito", "Fijo", "2026-03-01"],
  ["Seguro 360", "11953", "Banco", "Fijo", "2026-03-01"],
  ["uber eats", "18581", "Comida", "Variable", "2026-03-01"],
  ["Banco Chile","33112", "Credito", "Fijo", "2026-03-01"],
  ["bencina","49009", "Auto", "Variable", "2026-03-01"],
  ["Jumbo S4", "9870", "Supermercado", "Variable", "2026-03-01"],
  ["Estacionamiento", "3800", "Otros", "Variable", "2026-03-01"],
  ["Almacen s4", "13670", "Supermercado", "Variable", "2026-03-01"],
  ["Lider s4", "67161", "Supermercado", "Variable", "2026-03-01"],
  ["Seguro de proteccion","8367", "Banco", "Fijo", "2026-03-01"],
  ["pago", "67200", "Servicio", "Variable", "2026-04-01"],
  ["short y botallas decathlon", "33000", "Ropa y Accesorios", "Variable", "2026-04-01"],
  ["Banco Chile", "86914", "Credito", "Fijo", "2026-04-01"],
  ["Ajicito", "20460", "Comida", "Variable", "2026-04-01"],
  ["helados soft","2800", "Salidas", "Variable", "2026-04-01"],
  ["cosas bds y lapiz lopez", "5980", "Otros", "Variable", "2026-04-01"],
  ["fotos en piedra", "29980", "Otros", "Variable", "2026-04-01"],
  ["mercadolibre cosa", "5000", "Otros", "Variable", "2026-04-01"],
  ["Santa Isabel s1", "22810", "Supermercado", "Variable", "2026-04-01"],
  ["mercadolibre cosas", "13680", "Otros", "Variable", "2026-04-01"],
  ["cosas", "9700", "Otros", "Variable", "2026-04-01"],
  ["uber eats","11232", "", "Variable", "2026-04-01"],
  ["cosas", "27000", "Otros", "Variable", "2026-04-01"],
  ["cosas", "20030", "Otros", "Variable", "2026-04-01"],
  ["Almacen s1", "8650", "Supermercado", "Variable", "2026-04-01"],
  ["Gasto Comun", "75934", "Servicios", "Fijo", "2026-04-01"],
  ["Arriendo", "443520", "Servicios", "Fijo", "2026-04-01"],
  ["Almacen s2", "6690", "Supermercado", "Variable", "2026-04-01"],
  ["Lider s2", "7380", "Supermercado", "Variable", "2026-04-01"],
  ["Contribuciones", "40628", "Servicios", "Fijo", "2026-04-01"],
  ["Banco Chile", "86082", "Credito", "Fijo", "2026-04-01"],
  ["Cafe dunkin", "3090", "Salidas", "Variable", "2026-04-01"],
  ["Mama", "100000", "Otros", "Variable", "2026-04-01"],
  ["mercadolibre", "7460", "Otros", "Variable", "2026-04-01"],
  ["Remedios", "4690", "Medicina", "Variable", "2026-04-01"],
  ["mercadolibre", "5590", "Otros", "Variable", "2026-04-01"],
  ["Banco Chile", "84615", "Credito", "Fijo", "2026-04-01"],
  ["Alicates", "8570", "Otros", "Variable", "2026-04-01"],
  ["Almacen s2", "8440", "Supermercado", "Variable", "2026-04-01"],
  ["Lider s2", "111929", "Supermercado", "Variable", "2026-04-01"],
  ["Giro", "50000", "Banco", "Variable", "2026-04-01"],
  ["Desayuno burger", "6780", "Salidas", "Variable", "2026-04-01"],
  ["Helados la rosa", "7180", "Salidas", "Variable", "2026-04-01"],
  ["ENEL", "22924", "Servicios", "Fijo", "2026-04-01"],
  ["CAE", "46031", "Credito", "Fijo", "2026-04-01"],
  ["Cine con ale", "9900", "Salidas", "Variable", "2026-04-01"],
  ["Almacen s2", "6490", "Supermercado", "Variable", "2026-04-01"],
  ["Cosas", "15000", "Otros", "Variable", "2026-04-01"],
  ["Comida gatos", "36990", "Supermercado", "Variable", "2026-04-01"],
  ["Empanadas", "6000", "Comida", "Variable", "2026-04-01"],
  ["Alamacen s3", "2200", "Supermercado", "Variable", "2026-04-01"],
  ["Lider s3", "111318", "Supermercado", "Variable", "2026-04-01"],
  ["Hamburguesas", "12500", "Salidas", "Variable", "2026-04-01"],
  ["Bencina", "49532", "Auto", "Variable", "2026-04-01"],
  ["cosas", "7850", "Otros", "Variable", "2026-04-01"],
  ["Papajohns", "13000", "Salidas", "Variable", "2026-04-01"],
  ["Shawarmas", "21989", "Salidas", "Variable", "2026-04-01"],
  ["Internet Hogar", "21989", "Servicios", "Fijo", "2026-04-01"],
  ["Plan mobil", "17490", "Servicios", "Fijo", "2026-04-01"],
  ["Almacen s3", "6020", "Supermercado", "Variable", "2026-04-01"],
  ["Desayuno Burger", "6780", "Salidas", "Variable", "2026-04-01"],
  ["Test", "3040", "Medicina", "Variable", "2026-04-01"],
  ["Cafetano x2", "34580", "Otros", "Variable", "2026-04-01"],
  ["Almacen s4", "4600", "Supermercado", "Variable", "2026-04-01"],
  ["Santa Isabel s4", "28040", "Supermercado", "Variable", "2026-04-01"],
  ["Banco Falabella", "175500", "Credito", "Fijo", "2026-04-01"],
  ["Banco Chile", "85422", "Credito", "Fijo", "2026-04-01"]
]
